---
- name: If we're reinstalling we have some things to remove.
  yum:
    name: epel-release
    state: absent
    update_cache: yes
- name: Like the Postgres-Source repo.
  yum_repository:
    name: postgres
    description: Postgres-Source 
    baseurl: https://download.postgresql.org/pub/repos/yum/9.5/redhat/rhel-7-x86_64
    state: absent
- name: Remove CentOS-Vault
  yum_repository:
    name: CentOS-Vault
    description: Broken CentOS Repo
    baseurl: http://vault.centos.org/centos/7/os/Source
    state: absent
- name: No, really, remove CentOS-Vault
  file:
    dest: /etc/yum.repos.d/CentOS-Vault.repo
    state: absent
- name: And also the CentOS-Sources
  file:
    dest: /etc/yum.repos.d/CentOS-Sources.repo
    state: absent
- name: Install epel-release.
  yum:
    name: epel-release
    state: latest
    update_cache: yes
  # pgdg-centos95-9.5-3.noarch.rpm
- name: Install the PostgreSQL yum repo.
  yum_repository:
    name: postgres
    description: Yum repository for PostgreSQL. 
    baseurl: https://download.postgresql.org/pub/repos/yum/9.5/redhat/rhel-7-x86_64
    state: present
- name: Update current packages.
  yum:
    name: '*'
    state: latest
    update_cache: yes
- name: Install some more packages.
  yum:
    name: "{{ item }}" 
    state: latest
    update_cache: yes
  with_items: "{{ yum_packages }}"
...
# vim: ft=ansible :
