---
- name: Make the required directory.
  file:
    state: directory
    group: python
    mode: ug+rw
    owner: vagrant
    dest: /opt/python
- name: Extract the latest Python source.
  unarchive:
    src: https://www.python.org/ftp/python/2.7.13/Python-2.7.13.tgz
    dest: /tmp
    copy: no
- name: Configure, compile, and install same.
  shell: ./configure --prefix=/opt/python; make; make install
  args:
    chdir: /tmp/Python-2.7.13
- name: Remove the build directory.
  file:
    state: absent
    dest: /tmp/Python-2.7.13
- name: Update ownership of the python directory.
  file:
    owner: vagrant
    group: python
    state: directory
    recurse: yes
    dest: /opt/python
- name: Install pip into the new installation.
  shell: /opt/python/bin/python /tmp/get-pip.py
- name: Install some packages into the new installation. 
  pip:
    name: "{{ item }}"
    executable: /opt/python/bin/pip
    state: latest
  with_items:
    - ansible
    - flask
    - gunicorn
    - virtualenv
  become: yes
- name: Create a virtualenv with ansible in it for the users.
  pip:
    name: ansible
    virtualenv: "/home/{{ item }}"
    state: latest
    virtualenv_python: /opt/python/bin/python
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ users }}"
- name: Updating home directory permissions.
  file:
    dest: "/home/{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ item }}"
    group: python
  with_items: "{{ users }}"
- name: Create ansible for the system.
  pip:
    name: ansible
    virtualenv: /opt/ansible
    state: latest
  become_user: ansible
...
# vim: set ft=ansible ff=unix :
