---
- name: Make sure the required groups exist.
  group:
    name: "{{ item }}" 
    state: present
  become: yes
  with_items: "{{ user_groups }}"
- name: Clone the user prep playbooks.
  git:
    clone: yes
    repo: https://github.com/alexander-laughlin/user
    dest: /tmp/user
- name: Stat /usr/bin/vi
  stat: 
    path: /usr/bin/vi
  register: st
- debug:
    var: st
- name: Copy vim to where vi used to be. 
  shell: cp /usr/bin/vim /usr/bin/vi
  become: yes
  when: st.stat.islnk == false 
- name: Execute the playbooks.
  shell:  /tmp/bin/ansible-playbook /tmp/user/prepare.yml; /tmp/bin/ansible-playbook /tmp/user/skel.yml
- name: Remove the downloaded files.
  file:
    dest: /tmp/user
    state: absent
- name: Users for personal use.
  user:
    name: "{{ item }}" 
    state: present
    shell: /bin/bash
    home: "/home/{{ item }}"
    group: ansible
    generate_ssh_key: yes
    ssh_key_bits: 8192
    ssh_key_type: rsa
    groups: sudo,postgres,python,mongo
  become: yes
  with_items: "{{ users }}"
- name: Install the public key for users. 
  authorized_key:
    key: "{{ keys[item].public }}" 
    user: "{{ item }}" 
    state: present
  become: yes
  with_items:
    - duchess
- name: Add users for utilities. 
  user:
    name: "{{ item }}" 
    home: "/opt/{{ item }}"
    shell: /bin/bash
    group: "{{ item }}"
  become: yes
  become_user: root 
  with_items:
    - postgres
    - ansible
...
# vim: set ft=ansible ff=unix :
