#!/usr/bin/env python

import apache_beam
import sys
import unittest

from create_pipeline import CreatePipeline
from options import SetPipelineOptions

class TestCreatePipeline(unittest.TestCase):
    def setUp(self): 
        return None

    def test_pipeline_create(self):
        pipeline = CreatePipeline(options=None)
        self.assertIsInstance(pipeline, apache_beam.Pipeline) 

    def test_pipeline_options(self):
        spo = SetPipelineOptions()
        google_cloud = spo.config.get('google_cloud')
        spo.options = spo.set_pipeline()
        spo.set_google_cloud_options(google_cloud, spo.options)
        options = spo.set_runner(spo.options, spo.config.get('standard').get('runner')) 
        pipeline = CreatePipeline(options=options)
        pipeline = None
        self.assertIsInstance(pipeline, apache_beam.Pipeline)
        
    
class TestOptions(unittest.TestCase):
    def setUp(self):
        return None 

    def test_instantiate_class(self):
        options = SetPipelineOptions() 
        self.assertIsInstance(options, SetPipelineOptions) 

    def test_set_google_cloud_options(self):
        gco = SetPipelineOptions()
        google_cloud = gco.config.get("google_cloud")
        gco.pipeline = gco.set_pipeline()
        results = gco.set_google_cloud_options(google_cloud, gco.pipeline)
        self.assertIsInstance(results, apache_beam.utils.pipeline_options.GoogleCloudOptions)

    def test_set_pipeline(self): 
        pipeline = SetPipelineOptions().set_pipeline() 
        self.assertIsInstance(pipeline, apache_beam.utils.pipeline_options.PipelineOptions)

    def test_set_runner(self):
        set_pipeline_options = SetPipelineOptions()
        options = set_pipeline_options.set_pipeline() 
        runner = set_pipeline_options.set_runner(options, 'DataflowRunner')
        self.assertIsInstance(runner, apache_beam.utils.pipeline_options.PipelineOptions)
        

class TestStreamsRead(unittest.TestCase):
    def __init__():
        pass

class TestTracksRead(unittest.TestCase):
    def __init__():
       pass 

class TestUsersRead(unittest.TestCase):
    def __init__():
        pass

test_create_pipeline = unittest.TestLoader().loadTestsFromTestCase(TestCreatePipeline)
test_options = unittest.TestLoader().loadTestsFromTestCase(TestOptions)

suite = unittest.TestSuite([
    test_create_pipeline,
    test_options,
])
results = unittest.TextTestRunner(verbosity=5).run(suite)

if len(results.failures) > 0:
    sys.exit(-1)
